### ISSUE TITLE
iOS?

### ISSUE THREAD

**Issue by Kenner-G** [bharadwajpro/m3u8-player#1]

**Comment by bharadwajpro** [comment]
I haven't tested it on iOS but I think it works there too. Since this web app is served over https, browser may block http streams saying it as insecure. In Google Chrome desktop, we can just allow unsafe scripts by clicking on the right of address bar. Do let me know if it works or not.

**Comment by Kenner-G** [comment]
No, it does not work.

Also, I am noticing for live streams it takes around 10-15 seconds to load it up. Is there any way this can be decreased? My internet is fine.

**Comment by Kenner-G** [comment]
I am using a Chrome extension "Play HLS M3u8" and it literally loads a stream in milliseconds.

**Comment by Kenner-G** [comment]
Hello?

**Comment by bharadwajpro** [comment]
Hi. Thank you for your feedback. I just changed the domain name to something random 😜. I think the delay is because of `https`. Not sure but can you check now whether you have any speed issue? I am not noticing any delay now. If you still experience a delay, please share the m3u8 link and I will try debugging.

 I will be testing it on iOS too. Right now, I don't have an iOS device lying around.

**Comment by Kenner-G** [comment]
I have it on my own domain as well. I mean is there any way you could make it faster by an update to the code or?

**Comment by bharadwajpro** [comment]
Since iOS natively supports hls streaming. I added this part of code

`
else if (video.canPlayType('application/vnd.apple.mpegurl')) {
    video.src = 'https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u8';
    video.addEventListener('canplay',function() {
      video.play();
    });
  }
`
as given [here](https://github.com/video-dev/hls.js/#getting-started).
Check now. I think it should work now on iOS.
Regarding speed issue, I will work on it and get back to you.

**Comment by bharadwajpro** [comment]
Closing as the issue seems to be fixed.
